version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  groups:
    python-packages:
      patterns:
        - "*"
- package-ecosystem: "cargo"
  directory: "/rust/"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
