name: Example CI (not pure python)


on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_call:
    inputs:
      pure:
        type: boolean
        description: "The project is pure Python or not"
        default: false

jobs:
  check:
    name: Ruff/Rustfmt/cargo check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Run Ruff
        run: |
          uv venv
          uv pip install ruff
          uv run ruff check .

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Rustfmt
        run: cargo fmt --check

      - name: Run cargo check
        run: cargo check

  buildwheel:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: true

    runs-on: ${{ matrix.os }}
    needs: check

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

 # === Release Job ===
  release:
    runs-on: ubuntu-latest
    needs: buildwheel
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
