name: Python Coverage Report


on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # 使用するPythonのバージョンを指定

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run coverage
        run: |
          coverage run -m unittest discover  # unittestを用いたテストの実行
          coverage report  # ターミナル上に結果表示
          coverage html  # HTML形式でカバレッジレポートを出力

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: htmlcov  # HTMLレポートが出力されるディレクトリをアップロード
