name: Example


on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  coverage:
    uses: ./.github/workflows/coverage.yml

  CI:
    uses: ./.github/workflows/CI.yml
    permissions:
      contents: write